# Generated by Django 3.0.8 on 2020-07-28 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=60)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('full_salary', models.CharField(max_length=60)),
                ('salary_preview', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('greater_location', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
    ]
