# Generated by Django 3.0.8 on 2020-07-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='duration',
            new_name='type',
        ),
    ]
