# Generated by Django 3.0.8 on 2020-07-29 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200729_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='apply_url',
            field=models.URLField(help_text='The URL that the apply button will reroute to'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company',
            field=models.CharField(help_text='E.g. btecSolutions', max_length=60),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='The date and time the listing will be posted'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(help_text='The Markdown job description (max 4000 characters) See: https://www.markdownguide.org/basic-syntax/', max_length=4000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='full_salary',
            field=models.CharField(help_text="E.g. '£30,000 - £40,000 p.a.' or '£12.50 p.h.'", max_length=60),
        ),
        migrations.AlterField(
            model_name='listing',
            name='greater_location',
            field=models.CharField(blank=True, help_text='E.g. England', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.FileField(blank=True, help_text='SVG preferably - 40x40 Pixels only or distortion will occur', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='job_type',
            field=models.CharField(choices=[('C', 'Competition'), ('GS', 'Grant/Scholarship'), ('I', 'Internship'), ('P', 'Placement'), ('PT', 'Part Time'), ('FT', 'Full Time'), ('G', 'Graduate')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(help_text='E.g. London', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='mailto',
            field=models.URLField(help_text='The mailto link (preferably with ECSS in subject)', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='role',
            field=models.CharField(help_text='E.g. Software Engineer', max_length=60),
        ),
        migrations.AlterField(
            model_name='listing',
            name='salary_preview',
            field=models.CharField(help_text="E.g. '£30K - £40K' or '£12.50/HR'", max_length=20),
        ),
    ]
