# Generated by Django 3.0.8 on 2020-07-31 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200731_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='company',
            field=models.OneToOneField(help_text='The sponsor must be an existing Company', on_delete=django.db.models.deletion.CASCADE, to='jobs.Company'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(help_text='A paragraph or so describing the company'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='website',
            field=models.URLField(help_text="A URL to the company's website"),
        ),
    ]
