# Generated by Django 3.0.8 on 2020-07-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20200731_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.FileField(blank=True, default='logos/ecsslogo.png', help_text='SVG highly preferable - 1:1 aspect ratio only', upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(help_text='The Markdown job description. See: https://www.markdownguide.org/basic-syntax/'),
        ),
    ]
